- name: different filters
  host: localhost
  vars:
    users:
      alice:
        age: 30
        role: admin
      bob:
        age: 25
        role: developer
      charlie:
        age: 35
        role: tester
  tasks:
    - name: dictionary to items
      ansible.builtin.debug:
        msg: "Here is the items list {{users | dict2items}}"