- name: different filters
  hosts: localhost
  vars:
    numbers:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
  tasks:
    - name: dictionary to items
      ansible.builtin.debug:
        msg: "{{item}}"
      loop: "{{numbers}}"