- name: practicing filters
  hosts: localhost
  vars:
    greeting: "Hi Good Morning"
  tasks:
    - name: giving default values
      ansible.builtin.debug:
        msg: "Hi this is {{Course | default('Ansbile')}}"
    - name: upper case filter
      ansible.builtin.debug:
        msg: "Hi this is uppercase filter {{greeting | upper}}"
    - name: lower case filter
      ansible.builtin.debug:
        msg: "Hi this is lowercase filter {{greeting | lower}}"
  