- name: different filters
  hosts: localhost
  vars:
    numbers:
      - 1
      - 2
      - 3
      - 4
      - 5


  tasks:
    - name: dictionary to items
      ansible.builtin.debug:
        msg: "Square number of {{ item }} is {{ item | map('multiply', 2)}}" 
      loop: "{{ numbers }}"
      