- name: different filters
  hosts: localhost
  vars:
    users:
      alice: admin
      bob: developer
      aswani: devops
      sai: java


  tasks:
    - name: dictionary to items
      ansible.builtin.debug:
        msg: "Username is {{item.key}} User role is {{item.value}}."
      loop: "{{users}}"