- name: different filters
  hosts: localhost
  vars:
    numbers:
      - 1
      - 2
      - 3
      - 4
      - 5


  tasks:
    - name: Ensure community.general collection is installed
      ansible.builtin.collection:
          name: community.general
      
    - name: dictionary to items
      ansible.builtin.debug:
        msg: "Square number of {{ item }} is {{ item | multiply(item) }}" 
      loop: "{{ numbers }}"
      