- name: different filters
  hosts: localhost
  vars:
    fruits:
      - apple
      - banana
      - cherry
      - date
      - elderberry


  tasks:
    - name: dictionary to items
      ansible.builtin.debug:
        msg: "{{ item }} has morethan 5 letters" 
      loop: "{{fruits}}"
      when: "{{item | length > 5}}"