- name: variables
  hosts: localhost
  vars_files: #declaring the variables play level
    - vars.yaml
  tasks:
    - name: print info
      ansible.builtin.debug:
        msg: "Hi this is about learning {{Course}} from {{Trainer}} in duration {{Duration}}"